### ISSUE TITLE
Official RN devtools for @tanstack/query

### ISSUE THREAD

**Issue by adhorodyski** [bgaleotti/react-query-native-devtools#102]
Hey @bgaleotti :)

I noticed that [the original devtools currently don't support RN](https://tanstack.com/query/v4/docs/react/devtools), but then I've found your amazing flipper plugin!

At Callstack we've decided to help in this matter, are you open to making it official (`This community flipper plugin` in tanstack's docs?), or at least being mentioned?

**Comment by bgaleotti** [comment]
It is mentioned in the [docs](https://github.com/TanStack/query/blob/ff77512b6c99bef0555541429fdf27221d4d4412/docs/react/react-native.md#L8) but in the [React Native](https://tanstack.com/query/v4/docs/react/react-native) section.

**Comment by adhorodyski** [comment]
Omg, you're right! Funny I was able to miss something under a dedicated space 😅 I'll close the issue then, thanks for clarifying!
