### ISSUE TITLE
[issue]: ExceptionsManager.js:76 TypeError: Converting circular structure to JSON 

### ISSUE THREAD

**Issue by a-eid** [bgaleotti/react-query-native-devtools#15]
Hi, 

I'm trying to use the library but I'm facing this issue & not sure what's going wrong. 

![Screen Shot 2020-07-30 at 5 53 34 AM](https://user-images.githubusercontent.com/19273413/88878817-0229b000-d229-11ea-831b-5a426130e90b.png)

![Screen Shot 2020-07-30 at 5 53 53 AM](https://user-images.githubusercontent.com/19273413/88878831-0e157200-d229-11ea-951c-ac08f36a485f.png)

```
"react-native-flipper": "^0.51.0"
"react-query": "^2.5.8"
"react-query-native-devtools": "^0.1.5"
```

**Comment by bgaleotti** [comment]
@a-eid can you try `react-query-native-devtools@0.2.0-canary.0`?

**Comment by a-eid** [comment]
@bgaleotti yeah it works on the `canary.0` version.
