### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by JaapWeijland** [bgaleotti/react-query-native-devtools#17]
I'd like to debug React-Query on react native, but there is no manual on the difference (if there is any?) between the react native one and the react (web) one.

**Comment by bgaleotti** [comment]
Hi @JaapWeijland! What do you have in mind?

Maybe we can add some documentation at the root of this repo or an application example.

**Comment by vamshi9666** [comment]
check here. there is a readme , but caz of monorepo we have see inside packages/* directory.
