### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined at getQueryStatusLabel

### ISSUE THREAD

**Issue by signorettif** [bgaleotti/react-query-native-devtools#18]
Whenever performing even basic queries (see below), I always get the above error in Flipper.

Sample code to get the result:

```
const fetchRecipe = async ({id}) => {
    return (await fetch(`http://localhost:5000/api/`)).json();
  };
  const {data, isLoading, isError} = useQuery('expenses', fetchRecipe);
```

**Comment by bgaleotti** [comment]
Hi @signorettif! Can you give more context? Which `react-query`, `react-query-native-devtools` version are you using? Maybe a repro repo could be more helpful ..

**Comment by bgaleotti** [comment]
@signorettif can you try `flipper-plugin-react-query-native-devtools@0.4.0`?

**Comment by signorettif** [comment]
> Hi @signorettif! Can you give more context? Which `react-query`, `react-query-native-devtools` version are you using? Maybe a repro repo could be more helpful ..

Currently using `react-query: ˆ2.13.1` and `react-query-native-devtools: ˆ0.2.0`

 

> @signorettif can you try `flipper-plugin-react-query-native-devtools@0.4.0`?

Working perfectly sir. Thank you very much
