### ISSUE TITLE
Issue running React Query Devtools on React Native app

### ISSUE THREAD

**Issue by kamilkedzierski** [bgaleotti/react-query-native-devtools#22]
Hi! 🤙

Recently, I've implemented the React Query library in my React Native app. It works flawlessly! However, I'm facing issues with React Query Devtools 😢  Every time when I'm trying to enable it in the Flipper app it shows me the error attached below:
![image](https://user-images.githubusercontent.com/16210959/93217092-d88cff80-f768-11ea-9c8a-ff97e2fbe1ef.png)

Are you able to help me with that? 🥺

**Versions:**
"react": "16.13.1",
"react-native": "0.63.2",
"react-native-flipper": "^0.56.0",
"react-query-native-devtools": "^0.3.1",
"react-query": "^2.17.2",

**Comment by bgaleotti** [comment]
Hi @kamilkedzierski! Could you do a repro repo?

**Comment by bgaleotti** [comment]
@kamilkedzierski could you try `react-query-native-devtools@0.3.2-canary.0`?

**Comment by wconnorwalsh** [comment]
I also had this issue and the canary release has resolved it.

**Comment by bgaleotti** [comment]
Released `react-query-native-devtools@0.3.2`.

**Comment by kamilkedzierski** [comment]
Sorry for the late response, but I had too much work to do 😕  However, I can confirm that it works perfectly now! Thanks for the quick fix! 😊
