### ISSUE TITLE
Unable to resolve module 'flatted' from react query native devtools

### ISSUE THREAD

**Issue by halfasi** [bgaleotti/react-query-native-devtools#28]
Hi,

Today I tried to install the react query native devtools package in my RN Expo app, and the build fails automatically with this error:

Unable to resolve "flatted" from "node_modules/react-query-native-devtools/dist/react-query-native-devtools.cjs.production.min.js"

I implemented as many of the resolution steps that I could, but when I tried to reset the Metro Cache I got a warning that --reset-cache was not a valid command.

![image](https://user-images.githubusercontent.com/72921049/99901251-1ea49900-2cad-11eb-8746-9a1f1802b597.png)

Any help would be greatly appreciated.

Thank you

**Comment by bgaleotti** [comment]
@halfasi can you try [react-query-native-devtools@0.3.3-canary.0](https://www.npmjs.com/package/react-query-native-devtools/v/0.3.3-canary.0)?

BTW: I don't know if it will work with Expo ([related](https://expo.canny.io/feature-requests/p/integrate-flipper)).

**Comment by bgaleotti** [comment]
#32.
