### ISSUE TITLE
Support `react-query@^3`

### ISSUE THREAD

**Issue by bgaleotti** [bgaleotti/react-query-native-devtools#29]
Maybe we can [backport](https://github.com/pass-culture/pass-culture-app-native/pull/158/commits/9af7b8fb1a2558e9251e8e83eed959ba1686ea00) it.

**Comment by kopax** [comment]
Hi @bgaleotti it seems the backport is Incomplete, it still fail on refetch, perhaps this needs to be completed first.

**Comment by a-eid** [comment]
wondering if this v3 support planned anytime soon ?

**Comment by bgaleotti** [comment]
> wondering if this v3 support planned anytime soon ?

Try `react-query-native-devtools@^3`
