### ISSUE TITLE
What is ReactQueryCacheProvider in README.md 

### ISSUE THREAD

**Issue by kopax** [bgaleotti/react-query-native-devtools#36]
Hi,

I am joining an existing application which use:

- `react-query 3.1.1`
-  `flipper-plugin-react-query-native-devtools 0.5.0`
-  `react-query-native-devtools 0.3.2`
-  `react-native-flipper 0.61.0`

I  got an error when I click on `refetch` within `Flipper 0.72.0`.

After reading your `README.md`, it appear you have a `<ReactQueryCacheProvider />` which seems to be deprecated (https://stackoverflow.com/questions/65225014/reactquerycacheprovider-vs-reactqueryconfigprovider) component which we don't have, perhaps that's the cause of the error: 

```
Exception
queryCache.getQueries is not a function. (In 'queryCache.getQueries(function (query) {
    return query.queryHash === queryHash;
})', 'queryCache.getQueries' is undefined)
```

Do you have a clue why this is failing? Thanks for sharing!

**Comment by JosNun** [comment]
Looks like `react-query-native-devtools` doesn't yet support react-query v3 yet.

**Comment by bgaleotti** [comment]
> Hi,
> 
> I am joining an existing application which use:
> 
> * `react-query 3.1.1`
> * `flipper-plugin-react-query-native-devtools 0.5.0`
> * `react-query-native-devtools 0.3.2`
> * `react-native-flipper 0.61.0`
> 
> I got an error when I click on `refetch` within `Flipper 0.72.0`.
> 
> After reading your `README.md`, it appear you have a `<ReactQueryCacheProvider />` which seems to be deprecated ([stackoverflow.com/questions/65225014/reactquerycacheprovider-vs-reactqueryconfigprovider](https://stackoverflow.com/questions/65225014/reactquerycacheprovider-vs-reactqueryconfigprovider)) component which we don't have, perhaps that's the cause of the error:
> 
> ```
> Exception
> queryCache.getQueries is not a function. (In 'queryCache.getQueries(function (query) {
>     return query.queryHash === queryHash;
> })', 'queryCache.getQueries' is undefined)
> ```
> 
> Do you have a clue why this is failing? Thanks for sharing!

@kopax You were using `react-query@3.1.1` which was not yet supported. `<ReactQueryCacheProvider />` puts the cache on the context. In v3 you need to expose `<QueryClientProvider />` with your `QueryClient` instance.

You can try `react-query-native-devtools@^3` ([usage](https://github.com/bgaleotti/react-query-native-devtools/tree/master/packages/react-query-native-devtools#usage) updated).

Will close this. Feel free to fill an issue if ☝️  does not work.

**Comment by kopax** [comment]
Thanks for pinging here, we'll definitely have a look.
