### ISSUE TITLE
Plugin 'flipper-plugin-react-query-native-devtools' is unavailable

### ISSUE THREAD

**Issue by koreus7** [bgaleotti/react-query-native-devtools#60]
Flipper is telling me the plugin is unavailable.

Environment:
Seen On: iOS 14 simulator
OS: macOS 11.4
Flipper App: 0.96.1
"react-native": "0.64.0",
"react": "17.0.1",
"react-query-native-devtools": "^3.0.1",
"react-native-flipper": "^0.96.1"
"react-query": "^3.8.2",
"flipper-plugin-react-query-native-devtools": "^3.0.0",

```typescript
// App.ts
import {
  QueryClient,
  QueryClientProvider,
} from 'react-query';
import { addPlugin } from 'react-query-native-devtools';
const queryClient = new QueryClient();

if (__DEV__) {
  addPlugin({queryClient});
}
...
```

Things i've tried:

- Clearing packager cache and reloading the app
- Deleting rebuilding and reinstalling the app
- Restarting flipper
- Uninstalling and re-installing the flipper plugin
- Using the dynamic import as per README

**Comment by willerrodrigo** [comment]
Hi, @koreus7

Make sure you using the latest Flipper SDK on the project: https://fbflipper.com/docs/getting-started/react-native#using-the-latest-flipper-sdk

**Comment by Arcaneless** [comment]
I am having the same issue, I am using the latest flipper sdk.

**Comment by Arcaneless** [comment]
> I am having the same issue, I am using the latest Flipper sdk.

Reinstalling the flipper plugin works for me.
Search `flipper-plugin-react-query-native-devtools` in Flipper directly.

**Comment by bgaleotti** [comment]
> > I am having the same issue, I am using the latest Flipper sdk.
> 
> It turns out that I've installed a wrong Flipper plugin, it's the devtool from react-query official.
> Search `flipper-plugin-react-query-native-devtools` in Flipper directly.

@koreus7 could you check?

**Comment by apatel369** [comment]
same issue. I am using the latest flipper.

**Comment by DenisIrkhin** [comment]
Please try to catch an error to see if we have one.

And initiating `react-query-native-devtools` when we are in DEV env probably could be a better pattern @bgaleotti what's your view on that?

```ts
if (__DEV__) {
  const wrapper = { queryClient };
  import('react-query-native-devtools')
    .then(({ addPlugin }) => {
      addPlugin(wrapper);
    })
    .catch((err) => logger.info('Error when initializing React Query Flipper plug-in', err));
}
```

**Comment by apatel369** [comment]
Upgrade flipper to 0.127.0 and it is working now

**Comment by bgaleotti** [comment]
I will close this as looks like a misconfiguration problem.

**Comment by sregg** [comment]
I don't see `flipper-plugin-react-query-native-devtools` in Flipper. I only see `react-query-devtools` and `react-query-native-devtools`. I'm guessing the right one is `react-query-native-devtools`.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1479283/168616616-85511f45-ce81-4db7-8f28-fd0c45c67022.png">
