### ISSUE TITLE
Plugin is not bundled

### ISSUE THREAD

**Issue by mateuszwende** [bgaleotti/react-query-native-devtools#66]
I installed the plugin in the flipper, but it's not bundled and it's not being able to be used. See ss.
Did I missed something or anyone else also has this problem?

![image](https://user-images.githubusercontent.com/22375697/129683867-99f7c9e3-4a75-4b1c-a98e-58facde5e33a.png)

**Comment by apatel369** [comment]
facing same problem.

**Comment by apatel369** [comment]
Fixed by upgrading flipper to 0.127.0

**Comment by bgaleotti** [comment]
@mateuszwende `flipper-plugin-react-query-native-devtools` is not bundled, you have to install by yourself (which looks like you already have done).

You also need to follow the steps to install and configure [react-query-native-devtools](https://github.com/bgaleotti/react-query-native-devtools/blob/master/packages/react-query-native-devtools/README.md) in your application.
