### ISSUE TITLE
empty date explorer

### ISSUE THREAD

**Issue by lucasvieceli** [bgaleotti/react-query-native-devtools#69]
![image](https://user-images.githubusercontent.com/1795678/132989273-d5851765-fd0b-4c05-9ba5-739e21248b11.png)

I'm testing the flipper

but it's showing empty in data explorer

**Comment by bgaleotti** [comment]
@lucasvieceli can you share a repository to reproduce the problem?

**Comment by lucasvieceli** [comment]
new version fixed the problem,

you can close thanks :D

**Comment by ahmedu007** [comment]
Hey @bgaleotti 
Apologies for commenting on a closed issue, but is there any additional troubleshooting step that I could take to debug the issue? All I see is `React Query DevTools` in the `enabled` tab, but then there is no data

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/30743917/210856619-3dac35fc-f159-4742-b29b-b0a9995f2a34.png">

**Comment by bgaleotti** [comment]
@ahmedu007 could you please provide a minimal reproduction repository?

**Comment by ahmedu007** [comment]
I'll try to get something up tomorrow. My hunch is maybe it has something to do with the new version of `tanstack/query`? In the meantime, here are the dependencies we have 

```
"@tanstack/query-async-storage-persister": "4.13.0",
"@tanstack/react-query": "4.12.0",
"@tanstack/react-query-devtools": "4.12.0",
"@tanstack/react-query-persist-client": "4.13.0",
 "react": "18.1.0",
 "react-native": "0.70.2",
 ```

**Comment by bgaleotti** [comment]
> My hunch is maybe it has something to do with the new version of tanstack/query?

It shouldn't. The [example app](https://github.com/bgaleotti/react-query-native-devtools/blob/4716cd4ad857e376ce0ad930a99104fe34d4b8dc/apps/Time/package.json#L13) is using it.

> "@tanstack/react-query-devtools": "4.12.0",

This dependency is for web. If you are using `react-native` you shouldn't need it.

**Comment by ahmedu007** [comment]
Thanks for the example app @bgaleotti 

The web dependency was just me desperately trying to get it to work 😂 🙈 

I think it was just me being stupid, and the TS error wasn't helping either. Whilst creating a repro case I figured it out. Thanks for the quick responses 🙌
