### ISSUE TITLE
Refetch/Remove buttons in Flipper sidebar don't do action

### ISSUE THREAD

**Issue by salockhart** [bgaleotti/react-query-native-devtools#7]
I have installed react-query-native-devtools in my project, and the queries are appearing in the table without any problem.

When I select one of the queries and click "Refetch" or "Remove", nothing seems to happen.

I took a quick peek and I'm not sure that the call is making it to the client - console.log statements inside the handler aren't getting written out

Any tips?

**Comment by bgaleotti** [comment]
@salockhart they should be working, something like [this](https://streamable.com/388ueb).

Can you show your `package.json` and/or make a small reproduction repository?

**Comment by salockhart** [comment]
I did some more digging, and it seems that this is only replicable on Android.

Here's a demo repo: https://github.com/salockhart/FlipperReactQueryDemo

iOS works just fine, but Android still has the issue.

This sounds like something that I should raise with the Flipper repo - I will link back to this.

**Comment by salockhart** [comment]
@bgaleotti Looks like it might be an issue in the lib here, from the linked issue above:

>The issue is [here](https://github.com/bgaleotti/react-query-native-devtools/blob/fc6df266aa4e45da66b93c02fbf181f849f28fae/packages/flipper-plugin-react-query-native-devtools/src/index.tsx#L32-L38), you're sending a string as the parameters object in client.call(). This isn't supported, it should always be an object, e.g. {queryHash: query.queryHash} rather than just query.queryHash.
>It's just a coincidence that it happens to work in the iOS code path because there's one fewer translation layers.
>I see that in the API, params is of type any which is pretty misleading. Sorry about that, I'll try and get it fixed.

**Comment by bgaleotti** [comment]
@salockhart thanks! Will try to fix this today.

**Comment by bgaleotti** [comment]
@salockhart fixed in `react-query-native-devtools@0.1.3` and `flipper-plugin-react-query-native-devtools@0.3.1`.

**Comment by salockhart** [comment]
Great, thank you!
