### ISSUE TITLE
Error on react-query >1.5.0: JSON.stringify cannot serialize cyclic structures

### ISSUE THREAD

**Issue by salockhart** [bgaleotti/react-query-native-devtools#9]
I've updated react-query and I am now getting an error when the Flipper plugin attempts to send the query cache to Flipper.

<img width="300" alt="Screenshot 2020-05-27 at 12 06 40" src="https://user-images.githubusercontent.com/6651364/83011878-88036200-a012-11ea-867c-9e565bb104d5.png">

When I comment out the:

```
import('react-query-native-devtools').then(({ addPlugin }) => {
    addPlugin(queryCache);
  });
```

it works just fine.

This seems to be due to some change in the queryCache - is there a way that we can instead send just the data that we need? Do we need to instead raise this with react-query?

**Comment by bgaleotti** [comment]
@salockhart can you try `0.1.5` (skipped `0.1.4`, made a mistake while publishing it 😢)?

**Comment by salockhart** [comment]
that worked! thank you!
